name = "discohook-backup-importer"
main = "./build/index.js"
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
DISCOHOOK_ORIGIN = "https://discohook.app"

[env.preview]
name = "discohook-backup-importer-preview"

[env.preview.vars]
DISCOHOOK_ORIGIN = "https://preview.discohook.app"

[env.production.vars]
DISCOHOOK_ORIGIN = "https://discohook.app"
