name = "discohook-bot"
main = "./src/server.ts"
compatibility_date = "2023-05-18"
node_compat = true
services = [{ binding = "SITE", service = "discohook-site" }]

[vars]
ENVIRONMENT = "dev"
PREMIUM_SKUS = ["1249810125418397867"]
LIFETIME_SKU = "1266826214807572542"

[durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site" },
  { name = "SHARE_LINKS", class_name = "ShareLinks", script_name = "discohook-site" },
  { name = "EMOJIS", class_name = "EmojiManager" },
  { name = "SESSIONS", class_name = "SessionManager", script_name = "discohook-site" },
]

[[migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[[migrations]]
tag = "v2"
new_classes = ["EmojiManager"]

[env.preview]
route = { pattern = "bots.preview.discohook.app", custom_domain = true }
hyperdrive = [
  { binding = "HYPERDRIVE", id = "f8f714cc2701467cacf61b203ccd933a" },
]
services = [{ binding = "SITE", service = "discohook-site-preview" }]

[env.preview.durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site-preview" },
  { name = "SHARE_LINKS", class_name = "ShareLinks", script_name = "discohook-site-preview" },
  { name = "EMOJIS", class_name = "EmojiManager" },
  { name = "SESSIONS", class_name = "SessionManager", script_name = "discohook-site-preview" },
]

[[env.preview.migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[[env.preview.migrations]]
tag = "v2"
new_classes = ["EmojiManager"]

[env.preview.vars]
ENVIRONMENT = "preview"
DISCORD_APPLICATION_ID = "1259876010627694662"
PREMIUM_SKUS = []
LIFETIME_SKU = ""
DISCOHOOK_ORIGIN = "https://preview.discohook.app"

[env.production]
route = { pattern = "bots.discohook.app", custom_domain = true }
hyperdrive = [
  { binding = "HYPERDRIVE", id = "9568cd870bee47f3801c862de747ca94" },
]
services = [{ binding = "SITE", service = "discohook-site-production" }]

[env.production.placement]
mode = "smart"

[env.production.durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site-production" },
  { name = "SHARE_LINKS", class_name = "ShareLinks", script_name = "discohook-site-production" },
  { name = "EMOJIS", class_name = "EmojiManager" },
  { name = "SESSIONS", class_name = "SessionManager", script_name = "discohook-site-production" },
]

[[env.production.migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[[env.production.migrations]]
tag = "v2"
new_classes = ["EmojiManager"]

[env.production.vars]
ENVIRONMENT = "production"
DISCORD_APPLICATION_ID = "792842038332358656"
PREMIUM_SKUS = ["1249810125418397867"]
LIFETIME_SKU = "1266826214807572542"
DISCOHOOK_ORIGIN = "https://discohook.app"
GUILD_ID = "668218342779256857"
DONATOR_ROLE_ID = "747100568539103242"
SUBSCRIBER_ROLE_ID = "1251181202518315210"
