name = "discohook-bot"
main = "./src/server.ts"
compatibility_date = "2023-05-18"
node_compat = true
kv_namespaces = [
  { binding = "KV", id = "29967d1631d24846a448e8d2bcc49a5b", preview_id = "03d176ba6dbd4a2daa2f63f9f8f8bb4b" },
]
services = [{ binding = "SITE", service = "discohook-site" }]

[vars]
ENVIRONMENT = "dev"
PREMIUM_SKUS = ["1249810125418397867"]
LIFETIME_SKU = "1266826214807572542"

[durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site" },
]

[[migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[env.preview]
route = { pattern = "bots.preview.discohook.app", custom_domain = true }
kv_namespaces = [{ binding = "KV", id = "03d176ba6dbd4a2daa2f63f9f8f8bb4b" }]
hyperdrive = [
  { binding = "HYPERDRIVE", id = "f8f714cc2701467cacf61b203ccd933a" },
]
services = [{ binding = "SITE", service = "discohook-site-preview" }]

[env.preview.durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site-preview" },
]

[[env.preview.migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[env.preview.vars]
ENVIRONMENT = "preview"
DISCORD_APPLICATION_ID = "1259876010627694662"
PREMIUM_SKUS = []
LIFETIME_SKU = ""
DISCOHOOK_ORIGIN = "https://preview.discohook.app"

[env.production]
route = { pattern = "bots.discohook.app", custom_domain = true }
kv_namespaces = [{ binding = "KV", id = "29967d1631d24846a448e8d2bcc49a5b" }]
hyperdrive = [
  { binding = "HYPERDRIVE", id = "9568cd870bee47f3801c862de747ca94" },
]
services = [{ binding = "SITE", service = "discohook-site-production" }]

[env.production.durable_objects]
bindings = [
  { name = "COMPONENTS", class_name = "DurableComponentState" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner", script_name = "discohook-site-production" },
]

[[env.production.migrations]]
tag = "v1"
new_classes = ["DurableComponentState"]

[env.production.vars]
ENVIRONMENT = "production"
DISCORD_APPLICATION_ID = "792842038332358656"
PREMIUM_SKUS = ["1249810125418397867"]
LIFETIME_SKU = "1266826214807572542"
DISCOHOOK_ORIGIN = "https://discohook.app"
