##: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json

name = "discohook-site"
main = "./build/index.js"
compatibility_date = "2023-04-20"
node_compat = true
minify = true

kv_namespaces = [
  { binding = "KV", id = "29967d1631d24846a448e8d2bcc49a5b", preview_id = "03d176ba6dbd4a2daa2f63f9f8f8bb4b" },
]

services = [
  { binding = "CDN", service = "discohook-cdn", entrypoint = "UploaderService" },
]

[durable_objects]
bindings = [
  { name = "SCHEDULER", class_name = "DurableScheduler" },
  { name = "COMPONENTS", class_name = "DurableComponentState", script_name = "discohook-bot" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner" },
]

[[migrations]]
tag = "v1"
new_classes = [
  "DurableScheduler",
  "DurableComponentState",
  "DurableDraftComponentCleaner",
]

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "dev"
DISCORD_SUPPORT_INVITE_CODE = "discohook-668218342779256857"
BOTS_ORIGIN = "http://localhost:8787"
LEGACY_ORIGIN = "http://localhost:8789"
LINK_ORIGIN = "http://localhost:8790"
CDN_ORIGIN = "http://localhost:8791"

[env.preview]
name = "discohook-site-preview"
route = { pattern = "preview.discohook.app", custom_domain = true }
hyperdrive = [
  { binding = "HYPERDRIVE", id = "f8f714cc2701467cacf61b203ccd933a" },
]
kv_namespaces = [{ binding = "KV", id = "03d176ba6dbd4a2daa2f63f9f8f8bb4b" }]
services = [
  { binding = "CDN", service = "discohook-cdn", entrypoint = "UploaderService" },
  { binding = "BOT", service = "discohook-bot-preview" },
]

[env.preview.durable_objects]
bindings = [
  { name = "SCHEDULER", class_name = "DurableScheduler" },
  { name = "COMPONENTS", class_name = "DurableComponentState", script_name = "discohook-bot-preview" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner" },
]

[[env.preview.migrations]]
tag = "v1"
new_classes = [
  "DurableScheduler",
  "DurableComponentState",
  "DurableDraftComponentCleaner",
]

[env.preview.vars]
ENVIRONMENT = "preview"
DISCORD_CLIENT_ID = "1259876010627694662"
DISCORD_SUPPORT_INVITE_CODE = "discohook-668218342779256857"
BOTS_ORIGIN = "https://bots.preview.discohook.app"
LEGACY_ORIGIN = "https://discohook.org"
LINK_ORIGIN = "https://discohook.link"
CDN_ORIGIN = "https://cdn.discohook.app"

[env.production]
route = { pattern = "discohook.app", custom_domain = true }
hyperdrive = [
  { binding = "HYPERDRIVE", id = "b78274cce7d543ca952af16633c1885d" },
]
kv_namespaces = [{ binding = "KV", id = "29967d1631d24846a448e8d2bcc49a5b" }]
services = [
  { binding = "CDN", service = "discohook-cdn", entrypoint = "UploaderService" },
  { binding = "BOT", service = "discohook-bot" },
]

[env.production.durable_objects]
bindings = [
  { name = "SCHEDULER", class_name = "DurableScheduler" },
  { name = "COMPONENTS", class_name = "DurableComponentState", script_name = "discohook-bot" },
  { name = "DRAFT_CLEANER", class_name = "DurableDraftComponentCleaner" },
]

[[env.production.migrations]]
tag = "v1"
new_classes = [
  "DurableScheduler",
  "DurableComponentState",
  "DurableDraftComponentCleaner",
]

[env.production.vars]
ENVIRONMENT = "production"
DISCORD_CLIENT_ID = "792842038332358656"
DISCORD_SUPPORT_INVITE_CODE = "discohook-668218342779256857"
BOTS_ORIGIN = "https://bots.discohook.app"
LEGACY_ORIGIN = "https://discohook.org"
LINK_ORIGIN = "https://discohook.link"
CDN_ORIGIN = "https://cdn.discohook.app"
